#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Crosshair

#include "Basic.hpp"

#include "UI_Crosshair_classes.hpp"
#include "UI_Crosshair_parameters.hpp"


SDK_NAMESPACE_START

// Function UI_Crosshair.UI_Crosshair_C.ExecuteUbergraph_UI_Crosshair
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Crosshair_C::ExecuteUbergraph_UI_Crosshair(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "ExecuteUbergraph_UI_Crosshair");

	Params::UI_Crosshair_C_ExecuteUbergraph_UI_Crosshair Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Crosshair.UI_Crosshair_C.RefreshAmmoAmount
// (BlueprintCallable, BlueprintEvent)

void UUI_Crosshair_C::RefreshAmmoAmount()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "RefreshAmmoAmount");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Crosshair.UI_Crosshair_C.RefreshClipsize
// (BlueprintCallable, BlueprintEvent)

void UUI_Crosshair_C::RefreshClipsize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "RefreshClipsize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Crosshair.UI_Crosshair_C.HitIndicator
// (BlueprintCallable, BlueprintEvent)

void UUI_Crosshair_C::HitIndicator()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "HitIndicator");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Crosshair.UI_Crosshair_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Crosshair_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "Tick");

	Params::UI_Crosshair_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Crosshair.UI_Crosshair_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_Crosshair_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Crosshair.UI_Crosshair_C.ShowDot
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Crosshair_C::ShowDot()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "ShowDot");

	Params::UI_Crosshair_C_ShowDot Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Crosshair.UI_Crosshair_C.ShowCross
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Crosshair_C::ShowCross()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "ShowCross");

	Params::UI_Crosshair_C_ShowCross Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Crosshair.UI_Crosshair_C.ShowHammer
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Crosshair_C::ShowHammer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "ShowHammer");

	Params::UI_Crosshair_C_ShowHammer Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Crosshair.UI_Crosshair_C.ShowRoundcrosshair
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Crosshair_C::ShowRoundcrosshair()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "ShowRoundcrosshair");

	Params::UI_Crosshair_C_ShowRoundcrosshair Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Crosshair.UI_Crosshair_C.SetAmmo
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUI_Crosshair_C::SetAmmo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "SetAmmo");

	Params::UI_Crosshair_C_SetAmmo Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Crosshair.UI_Crosshair_C.ShowProgressBar
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Crosshair_C::ShowProgressBar()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "ShowProgressBar");

	Params::UI_Crosshair_C_ShowProgressBar Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Crosshair.UI_Crosshair_C.SetAmmoColor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateColor                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateColor UUI_Crosshair_C::SetAmmoColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "SetAmmoColor");

	Params::UI_Crosshair_C_SetAmmoColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Crosshair.UI_Crosshair_C.SetAmmoType
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_Crosshair_C::SetAmmoType()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "SetAmmoType");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Crosshair.UI_Crosshair_C.SetAmountColor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateColor                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateColor UUI_Crosshair_C::SetAmountColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "SetAmountColor");

	Params::UI_Crosshair_C_SetAmountColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Crosshair.UI_Crosshair_C.ShowAmmo
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Crosshair_C::ShowAmmo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "ShowAmmo");

	Params::UI_Crosshair_C_ShowAmmo Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Crosshair.UI_Crosshair_C.ShowHand
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Crosshair_C::ShowHand()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "ShowHand");

	Params::UI_Crosshair_C_ShowHand Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Crosshair.UI_Crosshair_C.ShowCrosshair
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Crosshair_C::ShowCrosshair()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "ShowCrosshair");

	Params::UI_Crosshair_C_ShowCrosshair Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Crosshair.UI_Crosshair_C.HideCompleteCrosshair
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Crosshair_C::HideCompleteCrosshair()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "HideCompleteCrosshair");

	Params::UI_Crosshair_C_HideCompleteCrosshair Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
