#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_DeathScreen

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"
#include "E_Weapons_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UI_DeathScreen.UI_DeathScreen_C
// 0x0048 (0x02A8 - 0x0260)
class UUI_DeathScreen_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_87;                                          // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_KillCard_C*                         UI_KillCard;                                       // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	float                                         RespawTimer;                                       // 0x0278(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MaxRespawnTime;                                    // 0x027C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          HeadShot;                                          // 0x0280(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_281[0x7];                                      // 0x0281(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_CapstanSloop_C*                     CapstanRef;                                        // 0x0288(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CursedText;                                        // 0x0290(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_UI_DeathScreen(int32 EntryPoint);
	void InitDeathScreen(const class FString& KillerPlayerName, float RespawnTime, bool HeadShot_0, E_Weapons Weapon, const struct FUniqueNetIdRepl& KillerId, int32 damage, int32 Kill_Distance, int32 Killer_HP, bool piratecurse);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void Construct();
	void CheckKillerName(const class FString& KillerName, const struct FUniqueNetIdRepl& KillerId, class FString* KillerNameOut, class ABP_PlayerState_C** PlayerStateRef);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_DeathScreen_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_DeathScreen_C")
	}
	static class UUI_DeathScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_DeathScreen_C>();
	}
};
DUMPER7_ASSERTS_UUI_DeathScreen_C;

SDK_NAMESPACE_END
