#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_DeadZoneColorPicker

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UI_DeadZoneColorPicker.UI_DeadZoneColorPicker_C
// 0x0028 (0x0288 - 0x0260)
class UUI_DeadZoneColorPicker_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UButton*                                Btn_Close;                                         // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                ColorPreview;                                      // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCP_ColorPicker_Wheel_C*                CP_ColorPicker_Wheel;                              // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_GameplayOptions_C*                  GameplayOptionsRef;                                // 0x0280(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UI_DeadZoneColorPicker(int32 EntryPoint);
	void BndEvt__CP_ColorPicker_Wheel_K2Node_ComponentBoundEvent_1_OnColorChanged__DelegateSignature(const struct FLinearColor& NewColor);
	void BndEvt__Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_DeadZoneColorPicker_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_DeadZoneColorPicker_C")
	}
	static class UUI_DeadZoneColorPicker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_DeadZoneColorPicker_C>();
	}
};
DUMPER7_ASSERTS_UUI_DeadZoneColorPicker_C;

SDK_NAMESPACE_END
