#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_FriendsListEntry_Epic_Steam

#include "Basic.hpp"

#include "UI_FriendsListEntry_Epic_Steam_classes.hpp"
#include "UI_FriendsListEntry_Epic_Steam_parameters.hpp"


SDK_NAMESPACE_START

// Function UI_FriendsListEntry_Epic_Steam.UI_FriendsListEntry_Epic_Steam_C.ExecuteUbergraph_UI_FriendsListEntry_Epic_Steam
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_FriendsListEntry_Epic_Steam_C::ExecuteUbergraph_UI_FriendsListEntry_Epic_Steam(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FriendsListEntry_Epic_Steam_C", "ExecuteUbergraph_UI_FriendsListEntry_Epic_Steam");

	Params::UI_FriendsListEntry_Epic_Steam_C_ExecuteUbergraph_UI_FriendsListEntry_Epic_Steam Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_FriendsListEntry_Epic_Steam.UI_FriendsListEntry_Epic_Steam_C.Received Avatar Friend
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Successful                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UTexture*                         Avatar                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FUniqueNetIdRepl&          User_ID                                                (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UUI_FriendsListEntry_Epic_Steam_C::Received_Avatar_Friend(bool Successful, class UTexture* Avatar, const struct FUniqueNetIdRepl& User_ID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FriendsListEntry_Epic_Steam_C", "Received Avatar Friend");

	Params::UI_FriendsListEntry_Epic_Steam_C_Received_Avatar_Friend Parms{};

	Parms.Successful = Successful;
	Parms.Avatar = Avatar;
	Parms.User_ID = std::move(User_ID);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_FriendsListEntry_Epic_Steam.UI_FriendsListEntry_Epic_Steam_C.Invite Friend
// (BlueprintCallable, BlueprintEvent)

void UUI_FriendsListEntry_Epic_Steam_C::Invite_Friend()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FriendsListEntry_Epic_Steam_C", "Invite Friend");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_FriendsListEntry_Epic_Steam.UI_FriendsListEntry_Epic_Steam_C.Created Party
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Successful                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_FriendsListEntry_Epic_Steam_C::Created_Party(bool Successful)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FriendsListEntry_Epic_Steam_C", "Created Party");

	Params::UI_FriendsListEntry_Epic_Steam_C_Created_Party Parms{};

	Parms.Successful = Successful;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_FriendsListEntry_Epic_Steam.UI_FriendsListEntry_Epic_Steam_C.BndEvt__InviteButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_FriendsListEntry_Epic_Steam_C::BndEvt__InviteButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FriendsListEntry_Epic_Steam_C", "BndEvt__InviteButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_FriendsListEntry_Epic_Steam.UI_FriendsListEntry_Epic_Steam_C.OnListItemObjectSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UObject*                          ListItemObject                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_FriendsListEntry_Epic_Steam_C::OnListItemObjectSet(class UObject* ListItemObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FriendsListEntry_Epic_Steam_C", "OnListItemObjectSet");

	Params::UI_FriendsListEntry_Epic_Steam_C_OnListItemObjectSet Parms{};

	Parms.ListItemObject = ListItemObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_FriendsListEntry_Epic_Steam.UI_FriendsListEntry_Epic_Steam_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_FriendsListEntry_Epic_Steam_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FriendsListEntry_Epic_Steam_C", "BP_OnItemSelectionChanged");

	Params::UI_FriendsListEntry_Epic_Steam_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_FriendsListEntry_Epic_Steam.UI_FriendsListEntry_Epic_Steam_C.BP_OnItemExpansionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsExpanded                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_FriendsListEntry_Epic_Steam_C::BP_OnItemExpansionChanged(bool bIsExpanded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FriendsListEntry_Epic_Steam_C", "BP_OnItemExpansionChanged");

	Params::UI_FriendsListEntry_Epic_Steam_C_BP_OnItemExpansionChanged Parms{};

	Parms.bIsExpanded = bIsExpanded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_FriendsListEntry_Epic_Steam.UI_FriendsListEntry_Epic_Steam_C.BP_OnEntryReleased
// (Event, Protected, BlueprintEvent)

void UUI_FriendsListEntry_Epic_Steam_C::BP_OnEntryReleased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FriendsListEntry_Epic_Steam_C", "BP_OnEntryReleased");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_FriendsListEntry_Epic_Steam.UI_FriendsListEntry_Epic_Steam_C.EnableInvitebutton
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_FriendsListEntry_Epic_Steam_C::EnableInvitebutton()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FriendsListEntry_Epic_Steam_C", "EnableInvitebutton");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_FriendsListEntry_Epic_Steam.UI_FriendsListEntry_Epic_Steam_C.GetInviteButtonColorAndOpacity
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UUI_FriendsListEntry_Epic_Steam_C::GetInviteButtonColorAndOpacity()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FriendsListEntry_Epic_Steam_C", "GetInviteButtonColorAndOpacity");

	Params::UI_FriendsListEntry_Epic_Steam_C_GetInviteButtonColorAndOpacity Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_FriendsListEntry_Epic_Steam.UI_FriendsListEntry_Epic_Steam_C.Get_FriendNameTxt_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUI_FriendsListEntry_Epic_Steam_C::Get_FriendNameTxt_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FriendsListEntry_Epic_Steam_C", "Get_FriendNameTxt_Text_0");

	Params::UI_FriendsListEntry_Epic_Steam_C_Get_FriendNameTxt_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_FriendsListEntry_Epic_Steam.UI_FriendsListEntry_Epic_Steam_C.Get_StatusBorder_BrushColor_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UUI_FriendsListEntry_Epic_Steam_C::Get_StatusBorder_BrushColor_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FriendsListEntry_Epic_Steam_C", "Get_StatusBorder_BrushColor_0");

	Params::UI_FriendsListEntry_Epic_Steam_C_Get_StatusBorder_BrushColor_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_FriendsListEntry_Epic_Steam.UI_FriendsListEntry_Epic_Steam_C.Get_EpicLogo_Visibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_FriendsListEntry_Epic_Steam_C::Get_EpicLogo_Visibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FriendsListEntry_Epic_Steam_C", "Get_EpicLogo_Visibility_0");

	Params::UI_FriendsListEntry_Epic_Steam_C_Get_EpicLogo_Visibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_FriendsListEntry_Epic_Steam.UI_FriendsListEntry_Epic_Steam_C.Get_SteamLogo_Visibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_FriendsListEntry_Epic_Steam_C::Get_SteamLogo_Visibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FriendsListEntry_Epic_Steam_C", "Get_SteamLogo_Visibility_0");

	Params::UI_FriendsListEntry_Epic_Steam_C_Get_SteamLogo_Visibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_FriendsListEntry_Epic_Steam.UI_FriendsListEntry_Epic_Steam_C.Get_FriendNameTxt_1_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUI_FriendsListEntry_Epic_Steam_C::Get_FriendNameTxt_1_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FriendsListEntry_Epic_Steam_C", "Get_FriendNameTxt_1_Text_0");

	Params::UI_FriendsListEntry_Epic_Steam_C_Get_FriendNameTxt_1_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_FriendsListEntry_Epic_Steam.UI_FriendsListEntry_Epic_Steam_C.Set Default Avatar Based on platform
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_FriendsListEntry_Epic_Steam_C::Set_Default_Avatar_Based_on_platform()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FriendsListEntry_Epic_Steam_C", "Set Default Avatar Based on platform");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_FriendsListEntry_Epic_Steam.UI_FriendsListEntry_Epic_Steam_C.Get_FriendStatusTxt_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUI_FriendsListEntry_Epic_Steam_C::Get_FriendStatusTxt_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FriendsListEntry_Epic_Steam_C", "Get_FriendStatusTxt_Text_0");

	Params::UI_FriendsListEntry_Epic_Steam_C_Get_FriendStatusTxt_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_FriendsListEntry_Epic_Steam.UI_FriendsListEntry_Epic_Steam_C.Get_InviteButton_bIsEnabled_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UUI_FriendsListEntry_Epic_Steam_C::Get_InviteButton_bIsEnabled_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FriendsListEntry_Epic_Steam_C", "Get_InviteButton_bIsEnabled_0");

	Params::UI_FriendsListEntry_Epic_Steam_C_Get_InviteButton_bIsEnabled_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_FriendsListEntry_Epic_Steam.UI_FriendsListEntry_Epic_Steam_C.GetVisibility_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_FriendsListEntry_Epic_Steam_C::GetVisibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FriendsListEntry_Epic_Steam_C", "GetVisibility_0");

	Params::UI_FriendsListEntry_Epic_Steam_C_GetVisibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_FriendsListEntry_Epic_Steam.UI_FriendsListEntry_Epic_Steam_C.Set Avatar
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Image                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_FriendsListEntry_Epic_Steam_C::Set_Avatar(class UObject* Image)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FriendsListEntry_Epic_Steam_C", "Set Avatar");

	Params::UI_FriendsListEntry_Epic_Steam_C_Set_Avatar Parms{};

	Parms.Image = Image;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
