#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_HammerAndBurdensSkinsList

#include "Basic.hpp"

#include "UI_HammerAndBurdensSkinsList_classes.hpp"
#include "UI_HammerAndBurdensSkinsList_parameters.hpp"


SDK_NAMESPACE_START

// Function UI_HammerAndBurdensSkinsList.UI_HammerAndBurdensSkinsList_C.ExecuteUbergraph_UI_HammerAndBurdensSkinsList
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_HammerAndBurdensSkinsList_C::ExecuteUbergraph_UI_HammerAndBurdensSkinsList(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HammerAndBurdensSkinsList_C", "ExecuteUbergraph_UI_HammerAndBurdensSkinsList");

	Params::UI_HammerAndBurdensSkinsList_C_ExecuteUbergraph_UI_HammerAndBurdensSkinsList Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_HammerAndBurdensSkinsList.UI_HammerAndBurdensSkinsList_C.ReloadWidgets
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    CurseBurdens_0                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_HammerAndBurdensSkinsList_C::ReloadWidgets(bool CurseBurdens_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HammerAndBurdensSkinsList_C", "ReloadWidgets");

	Params::UI_HammerAndBurdensSkinsList_C_ReloadWidgets Parms{};

	Parms.CurseBurdens_0 = CurseBurdens_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_HammerAndBurdensSkinsList.UI_HammerAndBurdensSkinsList_C.Scroll
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   ScrollValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_HammerAndBurdensSkinsList_C::Scroll(float ScrollValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HammerAndBurdensSkinsList_C", "Scroll");

	Params::UI_HammerAndBurdensSkinsList_C_Scroll Parms{};

	Parms.ScrollValue = ScrollValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_HammerAndBurdensSkinsList.UI_HammerAndBurdensSkinsList_C.Refresh
// (BlueprintCallable, BlueprintEvent)

void UUI_HammerAndBurdensSkinsList_C::Refresh()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HammerAndBurdensSkinsList_C", "Refresh");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_HammerAndBurdensSkinsList.UI_HammerAndBurdensSkinsList_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_HammerAndBurdensSkinsList_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HammerAndBurdensSkinsList_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_HammerAndBurdensSkinsList.UI_HammerAndBurdensSkinsList_C.UnequipAllWidgets
// (BlueprintCallable, BlueprintEvent)

void UUI_HammerAndBurdensSkinsList_C::UnequipAllWidgets()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HammerAndBurdensSkinsList_C", "UnequipAllWidgets");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_HammerAndBurdensSkinsList.UI_HammerAndBurdensSkinsList_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_HammerAndBurdensSkinsList_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HammerAndBurdensSkinsList_C", "Tick");

	Params::UI_HammerAndBurdensSkinsList_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_HammerAndBurdensSkinsList.UI_HammerAndBurdensSkinsList_C.AddWidget
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    DevItem                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UUI_HammerAndBurdenSkinEntry_C*   WidgetRef                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Level_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CurseBurden                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_HammerAndBurdensSkinsList_C::AddWidget(bool DevItem, class UUI_HammerAndBurdenSkinEntry_C* WidgetRef, int32 Level_0, bool CurseBurden)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HammerAndBurdensSkinsList_C", "AddWidget");

	Params::UI_HammerAndBurdensSkinsList_C_AddWidget Parms{};

	Parms.DevItem = DevItem;
	Parms.WidgetRef = WidgetRef;
	Parms.Level_0 = Level_0;
	Parms.CurseBurden = CurseBurden;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
