#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_LootChestScreen_LootBox

#include "Basic.hpp"

#include "UI_LootChestScreen_LootBox_classes.hpp"
#include "UI_LootChestScreen_LootBox_parameters.hpp"


SDK_NAMESPACE_START

// Function UI_LootChestScreen_LootBox.UI_LootChestScreen_LootBox_C.ExecuteUbergraph_UI_LootChestScreen_LootBox
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_LootChestScreen_LootBox_C::ExecuteUbergraph_UI_LootChestScreen_LootBox(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_LootChestScreen_LootBox_C", "ExecuteUbergraph_UI_LootChestScreen_LootBox");

	Params::UI_LootChestScreen_LootBox_C_ExecuteUbergraph_UI_LootChestScreen_LootBox Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_LootChestScreen_LootBox.UI_LootChestScreen_LootBox_C.BndEvt__Button_0_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_LootChestScreen_LootBox_C::BndEvt__Button_0_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_LootChestScreen_LootBox_C", "BndEvt__Button_0_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_LootChestScreen_LootBox.UI_LootChestScreen_LootBox_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_LootChestScreen_LootBox_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_LootChestScreen_LootBox_C", "Tick");

	Params::UI_LootChestScreen_LootBox_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_LootChestScreen_LootBox.UI_LootChestScreen_LootBox_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_LootChestScreen_LootBox_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_LootChestScreen_LootBox_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_LootChestScreen_LootBox.UI_LootChestScreen_LootBox_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_LootChestScreen_LootBox_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_LootChestScreen_LootBox_C", "PreConstruct");

	Params::UI_LootChestScreen_LootBox_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_LootChestScreen_LootBox.UI_LootChestScreen_LootBox_C.GetVisibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_LootChestScreen_LootBox_C::GetVisibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_LootChestScreen_LootBox_C", "GetVisibility_0");

	Params::UI_LootChestScreen_LootBox_C_GetVisibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_LootChestScreen_LootBox.UI_LootChestScreen_LootBox_C.Get_TextBlockAmount_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUI_LootChestScreen_LootBox_C::Get_TextBlockAmount_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_LootChestScreen_LootBox_C", "Get_TextBlockAmount_Text_0");

	Params::UI_LootChestScreen_LootBox_C_Get_TextBlockAmount_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_LootChestScreen_LootBox.UI_LootChestScreen_LootBox_C.GetbIsEnabled_1
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UUI_LootChestScreen_LootBox_C::GetbIsEnabled_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_LootChestScreen_LootBox_C", "GetbIsEnabled_1");

	Params::UI_LootChestScreen_LootBox_C_GetbIsEnabled_1 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_LootChestScreen_LootBox.UI_LootChestScreen_LootBox_C.GetVisibility_1
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_LootChestScreen_LootBox_C::GetVisibility_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_LootChestScreen_LootBox_C", "GetVisibility_1");

	Params::UI_LootChestScreen_LootBox_C_GetVisibility_1 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
