#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_NoMoreKicksPopup

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UI_NoMoreKicksPopup.UI_NoMoreKicksPopup_C
// 0x0020 (0x0280 - 0x0260)
class UUI_NoMoreKicksPopup_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       NewAnimation_1;                                    // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UButton*                                BtnClose;                                          // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             DisplayText;                                       // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UI_NoMoreKicksPopup(int32 EntryPoint);
	void BndEvt__BtnClose_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_NoMoreKicksPopup_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_NoMoreKicksPopup_C")
	}
	static class UUI_NoMoreKicksPopup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_NoMoreKicksPopup_C>();
	}
};
DUMPER7_ASSERTS_UUI_NoMoreKicksPopup_C;

SDK_NAMESPACE_END
