#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Party_Member_Username

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "SlateCore_structs.hpp"
#include "ST_Titles_renamed_structs.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function UI_Party_Member_Username.UI_Party_Member_Username_C.ExecuteUbergraph_UI_Party_Member_Username
// 0x0004 (0x0004 - 0x0000)
struct UI_Party_Member_Username_C_ExecuteUbergraph_UI_Party_Member_Username final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_Party_Member_Username_C_ExecuteUbergraph_UI_Party_Member_Username;

// Function UI_Party_Member_Username.UI_Party_Member_Username_C.Get Txt Level
// 0x0080 (0x0080 - 0x0000)
struct UI_Party_Member_Username_C_Get_Txt_Level final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0018(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0058(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0068(0x0018)()
};
DUMPER7_ASSERTS_UI_Party_Member_Username_C_Get_Txt_Level;

// Function UI_Party_Member_Username.UI_Party_Member_Username_C.Get Title Visibility
// 0x0006 (0x0006 - 0x0000)
struct UI_Party_Member_Username_C_Get_Title_Visibility final
{
public:
	ESlateVisibility                              ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_TextIsEmpty_ReturnValue;                  // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_Party_Member_Username_C_Get_Title_Visibility;

// Function UI_Party_Member_Username.UI_Party_Member_Username_C.Get Txt Title
// 0x0018 (0x0018 - 0x0000)
struct UI_Party_Member_Username_C_Get_Txt_Title final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
};
DUMPER7_ASSERTS_UI_Party_Member_Username_C_Get_Txt_Title;

// Function UI_Party_Member_Username.UI_Party_Member_Username_C.Get Cursed Visibility
// 0x0005 (0x0005 - 0x0000)
struct UI_Party_Member_Username_C_Get_Cursed_Visibility final
{
public:
	ESlateVisibility                              ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_Party_Member_Username_C_Get_Cursed_Visibility;

// Function UI_Party_Member_Username.UI_Party_Member_Username_C.Get Txt Cursed Wins
// 0x0030 (0x0030 - 0x0000)
struct UI_Party_Member_Username_C_Get_Txt_Cursed_Wins final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0018(0x0018)()
};
DUMPER7_ASSERTS_UI_Party_Member_Username_C_Get_Txt_Cursed_Wins;

// Function UI_Party_Member_Username.UI_Party_Member_Username_C.Get Level Visibility
// 0x0006 (0x0006 - 0x0000)
struct UI_Party_Member_Username_C_Get_Level_Visibility final
{
public:
	ESlateVisibility                              ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_Party_Member_Username_C_Get_Level_Visibility;

// Function UI_Party_Member_Username.UI_Party_Member_Username_C.Get Txt Username
// 0x0030 (0x0030 - 0x0000)
struct UI_Party_Member_Username_C_Get_Txt_Username final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0018(0x0018)()
};
DUMPER7_ASSERTS_UI_Party_Member_Username_C_Get_Txt_Username;

// Function UI_Party_Member_Username.UI_Party_Member_Username_C.Get Txt Title Color 
// 0x0028 (0x0028 - 0x0000)
struct UI_Party_Member_Username_C_Get_Txt_Title_Color_ final
{
public:
	struct FSlateColor                            ReturnValue;                                       // 0x0000(0x0028)(Parm, OutParm, ReturnParm)
};
DUMPER7_ASSERTS_UI_Party_Member_Username_C_Get_Txt_Title_Color_;

// Function UI_Party_Member_Username.UI_Party_Member_Username_C.Set Title
// 0x0078 (0x0078 - 0x0000)
struct UI_Party_Member_Username_C_Set_Title final
{
public:
	int32                                         New_Title_Index;                                   // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0008(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Conv_StringToName_ReturnValue;            // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FST_Titles_renamed                     CallFunc_GetDataTableRowFromName_OutRow;           // 0x0020(0x0050)(HasGetValueTypeHash)
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue;      // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_UI_Party_Member_Username_C_Set_Title;

// Function UI_Party_Member_Username.UI_Party_Member_Username_C.Get Txt Username Color
// 0x0028 (0x0028 - 0x0000)
struct UI_Party_Member_Username_C_Get_Txt_Username_Color final
{
public:
	struct FSlateColor                            ReturnValue;                                       // 0x0000(0x0028)(Parm, OutParm, ReturnParm)
};
DUMPER7_ASSERTS_UI_Party_Member_Username_C_Get_Txt_Username_Color;

// Function UI_Party_Member_Username.UI_Party_Member_Username_C.Is Leader Visibility
// 0x0005 (0x0005 - 0x0000)
struct UI_Party_Member_Username_C_Is_Leader_Visibility final
{
public:
	ESlateVisibility                              ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_Party_Member_Username_C_Is_Leader_Visibility;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
