#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_ReceivedItem

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "E_Items_structs.hpp"
#include "UMG_classes.hpp"
#include "E_ItemCategories_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UI_ReceivedItem.UI_ReceivedItem_C
// 0x0028 (0x0288 - 0x0260)
class UUI_ReceivedItem_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Anim;                                              // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Img_Icon;                                          // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Txt_Amount;                                        // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	E_Items                                       Item;                                              // 0x0280(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_281[0x3];                                      // 0x0281(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Amount;                                            // 0x0284(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UI_ReceivedItem(int32 EntryPoint);
	void Init();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_ReceivedItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_ReceivedItem_C")
	}
	static class UUI_ReceivedItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_ReceivedItem_C>();
	}
};
DUMPER7_ASSERTS_UUI_ReceivedItem_C;

SDK_NAMESPACE_END
