#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_ServerBrowserGame

#include "Basic.hpp"

#include "UI_ServerBrowserGame_classes.hpp"
#include "UI_ServerBrowserGame_parameters.hpp"


SDK_NAMESPACE_START

// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.ExecuteUbergraph_UI_ServerBrowserGame
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ServerBrowserGame_C::ExecuteUbergraph_UI_ServerBrowserGame(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "ExecuteUbergraph_UI_ServerBrowserGame");

	Params::UI_ServerBrowserGame_C_ExecuteUbergraph_UI_ServerBrowserGame Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.Join Server With Password
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    Password_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UUI_ServerBrowserGame_C::Join_Server_With_Password(const class FString& Password_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "Join Server With Password");

	Params::UI_ServerBrowserGame_C_Join_Server_With_Password Parms{};

	Parms.Password_0 = std::move(Password_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.Join Server
// (BlueprintCallable, BlueprintEvent)

void UUI_ServerBrowserGame_C::Join_Server()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "Join Server");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.BP_OnItemExpansionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsExpanded                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_ServerBrowserGame_C::BP_OnItemExpansionChanged(bool bIsExpanded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "BP_OnItemExpansionChanged");

	Params::UI_ServerBrowserGame_C_BP_OnItemExpansionChanged Parms{};

	Parms.bIsExpanded = bIsExpanded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_ServerBrowserGame_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "PreConstruct");

	Params::UI_ServerBrowserGame_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_ServerBrowserGame_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "BP_OnItemSelectionChanged");

	Params::UI_ServerBrowserGame_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.BP_OnEntryReleased
// (Event, Protected, BlueprintEvent)

void UUI_ServerBrowserGame_C::BP_OnEntryReleased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "BP_OnEntryReleased");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.BndEvt__Btn_Join_K2Node_ComponentBoundEvent_65_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_ServerBrowserGame_C::BndEvt__Btn_Join_K2Node_ComponentBoundEvent_65_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "BndEvt__Btn_Join_K2Node_ComponentBoundEvent_65_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.OnMouseLeave
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UUI_ServerBrowserGame_C::OnMouseLeave(const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "OnMouseLeave");

	Params::UI_ServerBrowserGame_C_OnMouseLeave Parms{};

	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.OnMouseEnter
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UUI_ServerBrowserGame_C::OnMouseEnter(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "OnMouseEnter");

	Params::UI_ServerBrowserGame_C_OnMouseEnter Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.OnListItemObjectSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UObject*                          ListItemObject                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ServerBrowserGame_C::OnListItemObjectSet(class UObject* ListItemObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "OnListItemObjectSet");

	Params::UI_ServerBrowserGame_C_OnListItemObjectSet Parms{};

	Parms.ListItemObject = ListItemObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.SetVersionColor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateColor                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateColor UUI_ServerBrowserGame_C::SetVersionColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "SetVersionColor");

	Params::UI_ServerBrowserGame_C_SetVersionColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.EnableJoinButton
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UUI_ServerBrowserGame_C::EnableJoinButton()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "EnableJoinButton");

	Params::UI_ServerBrowserGame_C_EnableJoinButton Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.SetStateColor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateColor                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateColor UUI_ServerBrowserGame_C::SetStateColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "SetStateColor");

	Params::UI_ServerBrowserGame_C_SetStateColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.SetStateText
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUI_ServerBrowserGame_C::SetStateText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "SetStateText");

	Params::UI_ServerBrowserGame_C_SetStateText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.ShowLocked
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_ServerBrowserGame_C::ShowLocked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "ShowLocked");

	Params::UI_ServerBrowserGame_C_ShowLocked Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.SetMapname
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUI_ServerBrowserGame_C::SetMapname()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "SetMapname");

	Params::UI_ServerBrowserGame_C_SetMapname Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.SetTODIcon
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UUI_ServerBrowserGame_C::SetTODIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "SetTODIcon");

	Params::UI_ServerBrowserGame_C_SetTODIcon Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.SetPlayerAmount
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUI_ServerBrowserGame_C::SetPlayerAmount()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "SetPlayerAmount");

	Params::UI_ServerBrowserGame_C_SetPlayerAmount Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.SetButtontext
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUI_ServerBrowserGame_C::SetButtontext()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "SetButtontext");

	Params::UI_ServerBrowserGame_C_SetButtontext Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.SetRelevance
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_ServerBrowserGame_C::SetRelevance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "SetRelevance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.SetRelevancyColor_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UUI_ServerBrowserGame_C::SetRelevancyColor_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "SetRelevancyColor_0");

	Params::UI_ServerBrowserGame_C_SetRelevancyColor_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.GetRelevancyColor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   Max                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UUI_ServerBrowserGame_C::GetRelevancyColor(float Max)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "GetRelevancyColor");

	Params::UI_ServerBrowserGame_C_GetRelevancyColor Parms{};

	Parms.Max = Max;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.SetRelevancyColor_20
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UUI_ServerBrowserGame_C::SetRelevancyColor_20()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "SetRelevancyColor_20");

	Params::UI_ServerBrowserGame_C_SetRelevancyColor_20 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.SetRelevancyColor_40
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UUI_ServerBrowserGame_C::SetRelevancyColor_40()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "SetRelevancyColor_40");

	Params::UI_ServerBrowserGame_C_SetRelevancyColor_40 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.SetRelevancyColor_60
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UUI_ServerBrowserGame_C::SetRelevancyColor_60()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "SetRelevancyColor_60");

	Params::UI_ServerBrowserGame_C_SetRelevancyColor_60 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.SetRelevancyColor_80
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UUI_ServerBrowserGame_C::SetRelevancyColor_80()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "SetRelevancyColor_80");

	Params::UI_ServerBrowserGame_C_SetRelevancyColor_80 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.SetServerName
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUI_ServerBrowserGame_C::SetServerName()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "SetServerName");

	Params::UI_ServerBrowserGame_C_SetServerName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.SetInfoColor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateColor                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateColor UUI_ServerBrowserGame_C::SetInfoColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "SetInfoColor");

	Params::UI_ServerBrowserGame_C_SetInfoColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.GetVisibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_ServerBrowserGame_C::GetVisibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "GetVisibility_0");

	Params::UI_ServerBrowserGame_C_GetVisibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.SetBgBorderBrush
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UUI_ServerBrowserGame_C::SetBgBorderBrush()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "SetBgBorderBrush");

	Params::UI_ServerBrowserGame_C_SetBgBorderBrush Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.SetJoinButton_ColorAndOpacity
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UUI_ServerBrowserGame_C::SetJoinButton_ColorAndOpacity()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "SetJoinButton_ColorAndOpacity");

	Params::UI_ServerBrowserGame_C_SetJoinButton_ColorAndOpacity Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.SetBackground_ColorAndOpacity
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UUI_ServerBrowserGame_C::SetBackground_ColorAndOpacity()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "SetBackground_ColorAndOpacity");

	Params::UI_ServerBrowserGame_C_SetBackground_ColorAndOpacity Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.PrepareStreamerName
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_ServerBrowserGame_C::PrepareStreamerName()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "PrepareStreamerName");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.SetFreeCrewSlotAmount
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUI_ServerBrowserGame_C::SetFreeCrewSlotAmount()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "SetFreeCrewSlotAmount");

	Params::UI_ServerBrowserGame_C_SetFreeCrewSlotAmount Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.SetFreeSlotColor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateColor                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateColor UUI_ServerBrowserGame_C::SetFreeSlotColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "SetFreeSlotColor");

	Params::UI_ServerBrowserGame_C_SetFreeSlotColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.SetIcon
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UUI_ServerBrowserGame_C::SetIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "SetIcon");

	Params::UI_ServerBrowserGame_C_SetIcon Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ServerBrowserGame.UI_ServerBrowserGame_C.SetMap
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUI_ServerBrowserGame_C::SetMap()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ServerBrowserGame_C", "SetMap");

	Params::UI_ServerBrowserGame_C_SetMap Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
