#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_StreamerMode_Switch

#include "Basic.hpp"

#include "UI_StreamerMode_Switch_classes.hpp"
#include "UI_StreamerMode_Switch_parameters.hpp"


SDK_NAMESPACE_START

// Function UI_StreamerMode_Switch.UI_StreamerMode_Switch_C.ExecuteUbergraph_UI_StreamerMode_Switch
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_StreamerMode_Switch_C::ExecuteUbergraph_UI_StreamerMode_Switch(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_StreamerMode_Switch_C", "ExecuteUbergraph_UI_StreamerMode_Switch");

	Params::UI_StreamerMode_Switch_C_ExecuteUbergraph_UI_StreamerMode_Switch Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_StreamerMode_Switch.UI_StreamerMode_Switch_C.BndEvt__StreamerButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_StreamerMode_Switch_C::BndEvt__StreamerButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_StreamerMode_Switch_C", "BndEvt__StreamerButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_StreamerMode_Switch.UI_StreamerMode_Switch_C.Get_IndicatorImg_Brush_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UUI_StreamerMode_Switch_C::Get_IndicatorImg_Brush_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_StreamerMode_Switch_C", "Get_IndicatorImg_Brush_0");

	Params::UI_StreamerMode_Switch_C_Get_IndicatorImg_Brush_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_StreamerMode_Switch.UI_StreamerMode_Switch_C.GetColorAndOpacity_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateColor                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateColor UUI_StreamerMode_Switch_C::GetColorAndOpacity_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_StreamerMode_Switch_C", "GetColorAndOpacity_0");

	Params::UI_StreamerMode_Switch_C_GetColorAndOpacity_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
