#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_ShipCosmeticGrid

#include "Basic.hpp"

#include "UI_CosmeticGridBase_classes.hpp"
#include "Engine_structs.hpp"
#include "E_SteamItemCategories_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UI_ShipCosmeticGrid.UI_ShipCosmeticGrid_C
// 0x0008 (0x0340 - 0x0338)
class UUI_ShipCosmeticGrid_C final : public UUI_CosmeticGridBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_UI_ShipCosmeticGrid_C;              // 0x0338(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_UI_ShipCosmeticGrid(int32 EntryPoint);
	void ChangeSortingDropdownSelection_1(const class FString& SelectedItem);
	void InitializeWidgets(bool InitializeSortingDropdown);
	void Scroll(float ScrollValue);
	void Refresh();
	void Construct();
	void AddToGrid(const struct FST_NewEOSInventoryItem_renamed& SteamItem, int32 Index_0, E_SteamItemCategories Category, int32 Rarity, bool Secundary, int32 Amount, class UUserWidget** Widget);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_ShipCosmeticGrid_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_ShipCosmeticGrid_C")
	}
	static class UUI_ShipCosmeticGrid_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_ShipCosmeticGrid_C>();
	}
};
DUMPER7_ASSERTS_UUI_ShipCosmeticGrid_C;

SDK_NAMESPACE_END
