#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_ShipStats

#include "Basic.hpp"

#include "UI_ShipStats_classes.hpp"
#include "UI_ShipStats_parameters.hpp"


SDK_NAMESPACE_START

// Function UI_ShipStats.UI_ShipStats_C.ExecuteUbergraph_UI_ShipStats
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ShipStats_C::ExecuteUbergraph_UI_ShipStats(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ShipStats_C", "ExecuteUbergraph_UI_ShipStats");

	Params::UI_ShipStats_C_ExecuteUbergraph_UI_ShipStats Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ShipStats.UI_ShipStats_C.SwitchedShip
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// E_ShipTypes                             ShipType_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ShipStats_C::SwitchedShip(E_ShipTypes ShipType_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ShipStats_C", "SwitchedShip");

	Params::UI_ShipStats_C_SwitchedShip Parms{};

	Parms.ShipType_0 = ShipType_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ShipStats.UI_ShipStats_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_ShipStats_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ShipStats_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ShipStats.UI_ShipStats_C.SetAmountNumbers
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UImage*>&                  ImageAray                                              (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// int32                                   Amount                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ShipStats_C::SetAmountNumbers(TArray<class UImage*>& ImageAray, int32 Amount)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ShipStats_C", "SetAmountNumbers");

	Params::UI_ShipStats_C_SetAmountNumbers Parms{};

	Parms.ImageAray = std::move(ImageAray);
	Parms.Amount = Amount;

	UObject::ProcessEvent(Func, &Parms);

	ImageAray = std::move(Parms.ImageAray);
}


// Function UI_ShipStats.UI_ShipStats_C.SetAmountDots
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UImage*>&                  ImageAray                                              (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// int32                                   Amount                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ShipStats_C::SetAmountDots(TArray<class UImage*>& ImageAray, int32 Amount)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ShipStats_C", "SetAmountDots");

	Params::UI_ShipStats_C_SetAmountDots Parms{};

	Parms.ImageAray = std::move(ImageAray);
	Parms.Amount = Amount;

	UObject::ProcessEvent(Func, &Parms);

	ImageAray = std::move(Parms.ImageAray);
}


// Function UI_ShipStats.UI_ShipStats_C.SetHullHealth
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_ShipStats_C::SetHullHealth()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ShipStats_C", "SetHullHealth");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ShipStats.UI_ShipStats_C.SetTopSpeed
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_ShipStats_C::SetTopSpeed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ShipStats_C", "SetTopSpeed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ShipStats.UI_ShipStats_C.SetTurningSpeed
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_ShipStats_C::SetTurningSpeed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ShipStats_C", "SetTurningSpeed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ShipStats.UI_ShipStats_C.SetAcceleration
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_ShipStats_C::SetAcceleration()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ShipStats_C", "SetAcceleration");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ShipStats.UI_ShipStats_C.SetDescription
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_ShipStats_C::SetDescription()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ShipStats_C", "SetDescription");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ShipStats.UI_ShipStats_C.FillCannonDots
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Amount                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ShipStats_C::FillCannonDots(int32 Amount)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ShipStats_C", "FillCannonDots");

	Params::UI_ShipStats_C_FillCannonDots Parms{};

	Parms.Amount = Amount;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ShipStats.UI_ShipStats_C.ShowLowerCannonDots
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_ShipStats_C::ShowLowerCannonDots()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ShipStats_C", "ShowLowerCannonDots");

	Params::UI_ShipStats_C_ShowLowerCannonDots Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ShipStats.UI_ShipStats_C.FillSwivelDots
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Amount                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ShipStats_C::FillSwivelDots(int32 Amount)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ShipStats_C", "FillSwivelDots");

	Params::UI_ShipStats_C_FillSwivelDots Parms{};

	Parms.Amount = Amount;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ShipStats.UI_ShipStats_C.ShowLowerSwivelDots
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_ShipStats_C::ShowLowerSwivelDots()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ShipStats_C", "ShowLowerSwivelDots");

	Params::UI_ShipStats_C_ShowLowerSwivelDots Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ShipStats.UI_ShipStats_C.GetVisibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_ShipStats_C::GetVisibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ShipStats_C", "GetVisibility_0");

	Params::UI_ShipStats_C_GetVisibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ShipStats.UI_ShipStats_C.Calculate Maxes
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_ShipStats_C::Calculate_Maxes()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ShipStats_C", "Calculate Maxes");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
