#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_ScoreBoardCrew

#include "Basic.hpp"

#include "UI_ScoreBoardCrew_classes.hpp"
#include "UI_ScoreBoardCrew_parameters.hpp"


SDK_NAMESPACE_START

// Function UI_ScoreBoardCrew.UI_ScoreBoardCrew_C.ExecuteUbergraph_UI_ScoreBoardCrew
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ScoreBoardCrew_C::ExecuteUbergraph_UI_ScoreBoardCrew(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ScoreBoardCrew_C", "ExecuteUbergraph_UI_ScoreBoardCrew");

	Params::UI_ScoreBoardCrew_C_ExecuteUbergraph_UI_ScoreBoardCrew Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ScoreBoardCrew.UI_ScoreBoardCrew_C.BndEvt__UI_ScoreBoardCrew_Team_ID_ComboBox_1_K2Node_ComponentBoundEvent_4_OnOpeningEvent__DelegateSignature
// (BlueprintEvent)

void UUI_ScoreBoardCrew_C::BndEvt__UI_ScoreBoardCrew_Team_ID_ComboBox_1_K2Node_ComponentBoundEvent_4_OnOpeningEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ScoreBoardCrew_C", "BndEvt__UI_ScoreBoardCrew_Team_ID_ComboBox_1_K2Node_ComponentBoundEvent_4_OnOpeningEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ScoreBoardCrew.UI_ScoreBoardCrew_C.BndEvt__UI_ScoreBoardCrew_Team_ID_ComboBox_1_K2Node_ComponentBoundEvent_7_OnSelectionChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const class FString&                    SelectedItem                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// ESelectInfo                             SelectionType                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ScoreBoardCrew_C::BndEvt__UI_ScoreBoardCrew_Team_ID_ComboBox_1_K2Node_ComponentBoundEvent_7_OnSelectionChangedEvent__DelegateSignature(const class FString& SelectedItem, ESelectInfo SelectionType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ScoreBoardCrew_C", "BndEvt__UI_ScoreBoardCrew_Team_ID_ComboBox_1_K2Node_ComponentBoundEvent_7_OnSelectionChangedEvent__DelegateSignature");

	Params::UI_ScoreBoardCrew_C_BndEvt__UI_ScoreBoardCrew_Team_ID_ComboBox_1_K2Node_ComponentBoundEvent_7_OnSelectionChangedEvent__DelegateSignature Parms{};

	Parms.SelectedItem = std::move(SelectedItem);
	Parms.SelectionType = SelectionType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ScoreBoardCrew.UI_ScoreBoardCrew_C.BndEvt__UI_ScoreBoardCrew_Team_ID_ComboBox_K2Node_ComponentBoundEvent_6_OnSelectionChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const class FString&                    SelectedItem                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// ESelectInfo                             SelectionType                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ScoreBoardCrew_C::BndEvt__UI_ScoreBoardCrew_Team_ID_ComboBox_K2Node_ComponentBoundEvent_6_OnSelectionChangedEvent__DelegateSignature(const class FString& SelectedItem, ESelectInfo SelectionType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ScoreBoardCrew_C", "BndEvt__UI_ScoreBoardCrew_Team_ID_ComboBox_K2Node_ComponentBoundEvent_6_OnSelectionChangedEvent__DelegateSignature");

	Params::UI_ScoreBoardCrew_C_BndEvt__UI_ScoreBoardCrew_Team_ID_ComboBox_K2Node_ComponentBoundEvent_6_OnSelectionChangedEvent__DelegateSignature Parms{};

	Parms.SelectedItem = std::move(SelectedItem);
	Parms.SelectionType = SelectionType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ScoreBoardCrew.UI_ScoreBoardCrew_C.BndEvt__UI_ScoreBoardCrew_Unlock_Button_1_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_ScoreBoardCrew_C::BndEvt__UI_ScoreBoardCrew_Unlock_Button_1_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ScoreBoardCrew_C", "BndEvt__UI_ScoreBoardCrew_Unlock_Button_1_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ScoreBoardCrew.UI_ScoreBoardCrew_C.BndEvt__UI_ScoreBoardCrew_Unlock_Button_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_ScoreBoardCrew_C::BndEvt__UI_ScoreBoardCrew_Unlock_Button_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ScoreBoardCrew_C", "BndEvt__UI_ScoreBoardCrew_Unlock_Button_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ScoreBoardCrew.UI_ScoreBoardCrew_C.BndEvt__UI_ScoreBoardCrew_Join_Button_1_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_ScoreBoardCrew_C::BndEvt__UI_ScoreBoardCrew_Join_Button_1_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ScoreBoardCrew_C", "BndEvt__UI_ScoreBoardCrew_Join_Button_1_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ScoreBoardCrew.UI_ScoreBoardCrew_C.BndEvt__UI_ScoreBoardCrew_Join_Button_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_ScoreBoardCrew_C::BndEvt__UI_ScoreBoardCrew_Join_Button_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ScoreBoardCrew_C", "BndEvt__UI_ScoreBoardCrew_Join_Button_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ScoreBoardCrew.UI_ScoreBoardCrew_C.ReConstruct ScoreBoard Crew
// (BlueprintCallable, BlueprintEvent)

void UUI_ScoreBoardCrew_C::ReConstruct_ScoreBoard_Crew()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ScoreBoardCrew_C", "ReConstruct ScoreBoard Crew");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ScoreBoardCrew.UI_ScoreBoardCrew_C.Initialize
// (BlueprintCallable, BlueprintEvent)

void UUI_ScoreBoardCrew_C::Initialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ScoreBoardCrew_C", "Initialize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ScoreBoardCrew.UI_ScoreBoardCrew_C.GetLineBgColor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UUI_ScoreBoardCrew_C::GetLineBgColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ScoreBoardCrew_C", "GetLineBgColor");

	Params::UI_ScoreBoardCrew_C_GetLineBgColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ScoreBoardCrew.UI_ScoreBoardCrew_C.Get Crew Ship Name
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUI_ScoreBoardCrew_C::Get_Crew_Ship_Name()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ScoreBoardCrew_C", "Get Crew Ship Name");

	Params::UI_ScoreBoardCrew_C_Get_Crew_Ship_Name Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ScoreBoardCrew.UI_ScoreBoardCrew_C.Get Defeated Visibility
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_ScoreBoardCrew_C::Get_Defeated_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ScoreBoardCrew_C", "Get Defeated Visibility");

	Params::UI_ScoreBoardCrew_C_Get_Defeated_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ScoreBoardCrew.UI_ScoreBoardCrew_C.Update Ship Icon
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_ScoreBoardCrew_C::Update_Ship_Icon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ScoreBoardCrew_C", "Update Ship Icon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ScoreBoardCrew.UI_ScoreBoardCrew_C.Update Crew Members
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_ScoreBoardCrew_C::Update_Crew_Members()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ScoreBoardCrew_C", "Update Crew Members");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ScoreBoardCrew.UI_ScoreBoardCrew_C.Large Team Visibility
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_ScoreBoardCrew_C::Large_Team_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ScoreBoardCrew_C", "Large Team Visibility");

	Params::UI_ScoreBoardCrew_C_Large_Team_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ScoreBoardCrew.UI_ScoreBoardCrew_C.Small Team Visibility
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_ScoreBoardCrew_C::Small_Team_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ScoreBoardCrew_C", "Small Team Visibility");

	Params::UI_ScoreBoardCrew_C_Small_Team_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ScoreBoardCrew.UI_ScoreBoardCrew_C.Generate Team Options
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_ScoreBoardCrew_C::Generate_Team_Options()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ScoreBoardCrew_C", "Generate Team Options");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ScoreBoardCrew.UI_ScoreBoardCrew_C.Get Moderator Visibility
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_ScoreBoardCrew_C::Get_Moderator_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ScoreBoardCrew_C", "Get Moderator Visibility");

	Params::UI_ScoreBoardCrew_C_Get_Moderator_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
