#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_TeleportEffect

#include "Basic.hpp"

#include "UI_TeleportEffect_classes.hpp"
#include "UI_TeleportEffect_parameters.hpp"


SDK_NAMESPACE_START

// Function UI_TeleportEffect.UI_TeleportEffect_C.ExecuteUbergraph_UI_TeleportEffect
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_TeleportEffect_C::ExecuteUbergraph_UI_TeleportEffect(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TeleportEffect_C", "ExecuteUbergraph_UI_TeleportEffect");

	Params::UI_TeleportEffect_C_ExecuteUbergraph_UI_TeleportEffect Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_TeleportEffect.UI_TeleportEffect_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_TeleportEffect_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TeleportEffect_C", "Tick");

	Params::UI_TeleportEffect_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_TeleportEffect.UI_TeleportEffect_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_TeleportEffect_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TeleportEffect_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
