#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Version

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UI_Version.UI_Version_C
// 0x0018 (0x0278 - 0x0260)
class UUI_Version_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCanvasPanel*                           CanvasPanel_0;                                     // 0x0268(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Txt_Version;                                       // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UI_Version(int32 EntryPoint);
	void Construct();
	ESlateVisibility GetVisibility_0();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_Version_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_Version_C")
	}
	static class UUI_Version_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Version_C>();
	}
};
DUMPER7_ASSERTS_UUI_Version_C;

SDK_NAMESPACE_END
