#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_VehicleWidgetBase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UI_VehicleWidgetBase.UI_VehicleWidgetBase_C
// 0x0020 (0x0280 - 0x0260)
class UUI_VehicleWidgetBase_C : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCanvasPanel*                           CanvasPanel_0;                                     // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ABP_VehicleBase_C*                      VehicleRef;                                        // 0x0270(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_Character_C*                        CharacterRef;                                      // 0x0278(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UI_VehicleWidgetBase(int32 EntryPoint);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void SetVehicleRef(class ABP_VehicleBase_C* Vehicle_Reference);
	void SetCharacterRef(class ABP_Character_C* Character_Reference);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_VehicleWidgetBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_VehicleWidgetBase_C")
	}
	static class UUI_VehicleWidgetBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_VehicleWidgetBase_C>();
	}
};
DUMPER7_ASSERTS_UUI_VehicleWidgetBase_C;

SDK_NAMESPACE_END
