#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_WinningScreen_Trophy

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"
#include "E_ScoreType_structs.hpp"
#include "SlateCore_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UI_WinningScreen_Trophy.UI_WinningScreen_Trophy_C
// 0x0098 (0x02F8 - 0x0260)
class UUI_WinningScreen_Trophy_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       RewardsFadeIn;                                     // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       XPAnim;                                            // 0x0270(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Image_12;                                          // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_13;                                          // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Txt_Player_Name;                                   // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Txt_Points_Description;                            // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Txt_Title;                                         // 0x0298(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	E_ScoreType                                   Score_Type;                                        // 0x02A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_2A1[0x7];                                      // 0x02A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            Tint;                                              // 0x02A8(0x0028)(Edit, BlueprintVisible, ExposeOnSpawn)
	class UTexture2D*                             Trophy_Image;                                      // 0x02D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	int32                                         HighestScore;                                      // 0x02D8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2DC[0x4];                                      // 0x02DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   PlayerName;                                        // 0x02E0(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_UI_WinningScreen_Trophy(int32 EntryPoint);
	void Construct();
	void Set_Best_Score();
	void CheckIfSelf(const class FText& Name_0, class ABP_PlayerState_C* PlayerState, class FText* Output, bool* IsYou, struct FSlateColor* SelfColor, struct FLinearColor* SelfColor_SpecifiedColor, ESlateColorStylingMode* SelfColor_ColorUseRule);
	class FText Get_Title();
	class FText Get_Score_Text();
	void Set_Best_Name(class ABP_PlayerState_C* Player_State);
	class FText Get_Txt_Player_Name_Text_0();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_WinningScreen_Trophy_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_WinningScreen_Trophy_C")
	}
	static class UUI_WinningScreen_Trophy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_WinningScreen_Trophy_C>();
	}
};
DUMPER7_ASSERTS_UUI_WinningScreen_Trophy_C;

SDK_NAMESPACE_END
