#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_YouKilledInfo

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UI_YouKilledInfo.UI_YouKilledInfo_C
// 0x0048 (0x02A8 - 0x0260)
class UUI_YouKilledInfo_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       KillPop;                                           // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UVerticalBox*                           KillFeedBox;                                       // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_90;                                      // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_YouKilledName_C*                    UI_YouKilledName;                                  // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ABP_Controller_C*                       ControllerRef;                                     // 0x0288(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         KillMultiplier;                                    // 0x0290(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_294[0x4];                                      // 0x0294(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 NameToAdd;                                         // 0x0298(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UI_YouKilledInfo(int32 EntryPoint);
	void AddKill(const class FString& PlayerName, int32 KillerId, bool CursedPlayer_);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void Construct();
	class FText GetKills();
	ESlateVisibility ShowKills();
	void CheckKillerName(const class FString& KillerName, int32 KillerId, class FString* KillerNameOut);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_YouKilledInfo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_YouKilledInfo_C")
	}
	static class UUI_YouKilledInfo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_YouKilledInfo_C>();
	}
};
DUMPER7_ASSERTS_UUI_YouKilledInfo_C;

SDK_NAMESPACE_END
