#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WaterSettings

#include "Basic.hpp"

#include "FetchLengths_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "WindSpeeds_structs.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass WaterSettings.WaterSettings_C
// 0x01D8 (0x03F8 - 0x0220)
class AWaterSettings_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	EWindSpeeds                                   WindSpeed;                                         // 0x0230(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFetchLengths                                 FetchLength;                                       // 0x0231(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_232[0x2];                                      // 0x0232(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         nWaves;                                            // 0x0234(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         nWaves_mod;                                        // 0x0238(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         nWindSpeeds;                                       // 0x023C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<float>                                 A;                                                 // 0x0240(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<float>                                 k1;                                                // 0x0250(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<float>                                 k2;                                                // 0x0260(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<float>                                 omega;                                             // 0x0270(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<float>                                 phi;                                               // 0x0280(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	int32                                         RandomPhaseSeed;                                   // 0x0290(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Refresh;                                           // 0x0294(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_295[0x3];                                      // 0x0295(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRandomStream                          RandomStreamPhase;                                 // 0x0298(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor)
	float                                         SeaLevel;                                          // 0x02A0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2A4[0x4];                                      // 0x02A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 A_orig;                                            // 0x02A8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	float                                         A_Multiplier;                                      // 0x02B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bSeaStateTransition;                               // 0x02BC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2BD[0x3];                                      // 0x02BD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 A_Target;                                          // 0x02C0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<float>                                 k1_Target;                                         // 0x02D0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<float>                                 k2_Target;                                         // 0x02E0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<float>                                 omega_Target;                                      // 0x02F0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<float>                                 phi_Target;                                        // 0x0300(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<float>                                 A_Old;                                             // 0x0310(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<float>                                 k1_Old;                                            // 0x0320(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<float>                                 k2_Old;                                            // 0x0330(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<float>                                 omega_Old;                                         // 0x0340(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<float>                                 phi_Old;                                           // 0x0350(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	float                                         TransitionStartTime;                               // 0x0360(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TransitionEndTime;                                 // 0x0364(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<float>                                 omega_dot;                                         // 0x0368(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	float                                         TransitionTime;                                    // 0x0378(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_37C[0x4];                                      // 0x037C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 k_mag_Old;                                         // 0x0380(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<float>                                 k_mag_Target;                                      // 0x0390(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<float>                                 k_angle_Old;                                       // 0x03A0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<float>                                 k_angle_Target;                                    // 0x03B0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FVector2D                              CameraLocationStart;                               // 0x03C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bDebug;                                            // 0x03C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3C9[0x3];                                      // 0x03C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         WindSpeed_Target;                                  // 0x03CC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         FetchLength_Target;                                // 0x03D0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         WindSpeedCurrent;                                  // 0x03D4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         FetchLengthCurrent;                                // 0x03D8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EWindSpeeds                                   WindSpeedTargetEnum;                               // 0x03DC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFetchLengths                                 FetchLengthTargetEnum;                             // 0x03DD(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3DE[0x2];                                      // 0x03DE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         TransitionAlpha;                                   // 0x03E0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         GameTime;                                          // 0x03E4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         GameTimeOffset;                                    // 0x03E8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3EC[0x4];                                      // 0x03EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AWaterPlane_C*                          WaterPlaneRef;                                     // 0x03F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WaterSettings(int32 EntryPoint);
	void ReceiveTick(float DeltaSeconds);
	void ConstructionEvent();
	void ReceiveBeginPlay();
	void UserConstructionScript();
	void CalculateDeltaNormal(const struct FVector2D& InitialLocation, int32 Accuracy_10_100_, float ZoneWaterHeight, struct FVector* Delta, struct FVector* Normal);
	void CalculateDeltaOnly(const struct FVector2D& InitialLocation, float ZoneWaterHeight, int32 Accuracy_10_28_, struct FVector* Delta);
	void GerstnerWaveDeltaOnly(int32 WaveIndex, const struct FVector2D& InitialLocation, struct FVector* deltaOut);
	void GerstnerWaveDeltaQ(int32 WaveIndex, const struct FVector2D& InitialLocation, struct FVector* deltaOut, struct FVector* Q_Out);
	void GenWareParamArrays(TArray<float>& A_0, TArray<float>& k1_0, TArray<float>& k2_0, TArray<float>& omega_0, int32 WindSpeedIndex, int32 FetchIndex);
	void ChangeSeaState(EWindSpeeds NewWindSpeed, EFetchLengths NewFetchLength, float TransitionTimeSeconds);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WaterSettings_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WaterSettings_C")
	}
	static class AWaterSettings_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWaterSettings_C>();
	}
};
DUMPER7_ASSERTS_AWaterSettings_C;

SDK_NAMESPACE_END
