#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WindSpeeds

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum WindSpeeds.WindSpeeds
// NumValues: 0x000E
enum class EWindSpeeds : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator10                          = 1,
	NewEnumerator1                           = 2,
	NewEnumerator11                          = 3,
	NewEnumerator2                           = 4,
	NewEnumerator12                          = 5,
	NewEnumerator3                           = 6,
	NewEnumerator4                           = 7,
	NewEnumerator5                           = 8,
	NewEnumerator6                           = 9,
	NewEnumerator7                           = 10,
	NewEnumerator8                           = 11,
	NewEnumerator9                           = 12,
	WindSpeeds_MAX                           = 13,
};

SDK_NAMESPACE_END
